name = "WasmCompiler"
uuid = "d6c8c267-1a52-47cb-afc2-bc072b58c422"
authors = ["Paul <paul@plutojl.org>"]
version = "0.1.0"

[deps]
Binaryen_jll = "a54ac8ab-712d-5a0e-8e11-9296c0d3c20e"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Wasmtime = "f519113a-1485-4b12-af44-dbf9b5a2f6b4"

[targets]
test = ["Test", "Wasmtime"]
